/**
 * Datos quemados para H&B Importaciones
 * Productos, usuarios, categorías y configuraciones del sistema
 */

const HBDATA = {
  // Usuarios demo del sistema
  users: [
    {
      id: 'u1',
      role: 'admin',
      name: 'Administrador',
      email: 'admin@hb.local',
      password: 'admin123',
      active: true,
      createdAt: '2024-01-01',
      lastLogin: null
    },
    {
      id: 'd1',
      role: 'distributor',
      name: 'Distribuidora Alfa',
      email: 'distri@hb.local',
      password: 'distri123',
      active: true,
      whatsapp: '+573001112233',
      createdAt: '2024-01-02',
      lastLogin: null
    },
    {
      id: 'c1',
      role: 'client',
      name: 'Cliente Demo',
      email: 'cliente@hb.local',
      password: 'cliente123',
      active: true,
      phone: '+573001112234',
      createdAt: '2024-01-03',
      lastLogin: null
    },
    {
      id: 'c2',
      role: 'client',
      name: 'María Pérez',
      email: 'maria.perez@email.com',
      password: 'cliente123',
      active: true,
      phone: '+573001112240',
      whatsapp: '+573001112240',
      createdAt: '2024-01-10',
      lastLogin: null
    },
    {
      id: 'c3',
      role: 'client',
      name: 'Carlos López',
      email: 'carlos.lopez@email.com',
      password: 'cliente123',
      active: true,
      phone: '+573001112241',
      whatsapp: '+573001112241',
      createdAt: '2024-01-15',
      lastLogin: null
    },
    {
      id: 'c4',
      role: 'client',
      name: 'Ana García',
      email: 'ana.garcia@email.com',
      password: 'cliente123',
      active: false,
      phone: '+573001112242',
      whatsapp: '+573001112242',
      createdAt: '2024-01-20',
      lastLogin: null
    },
    {
      id: 'c5',
      role: 'client',
      name: 'Luis Martínez',
      email: 'luis.martinez@email.com',
      password: 'cliente123',
      active: true,
      phone: '+573001112243',
      whatsapp: '+573001112243',
      createdAt: '2024-01-25',
      lastLogin: null
    },
    {
      id: 'd2',
      role: 'distributor',
      name: 'Distribuidora Beta',
      email: 'distri.beta@hb.local',
      password: 'distri123',
      active: true,
      whatsapp: '+573001112244',
      createdAt: '2024-01-05',
      lastLogin: null
    },
    {
      id: 'd3',
      role: 'distributor',
      name: 'Importaciones Gamma',
      email: 'import.gamma@hb.local',
      password: 'distri123',
      active: true,
      whatsapp: '+573001112245',
      createdAt: '2024-01-12',
      lastLogin: null
    },
    // Datos de asesores (no son usuarios de la plataforma, solo datos para gestión)
    {
      id: 'ase1',
      type: 'asesor',
      name: 'María González',
      email: 'maria.gonzalez@hb.local',
      phone: '+573001112236',
      whatsapp: '+573001112236',
      active: true,
      department: 'Ventas',
      position: 'Asesor Senior',
      hireDate: '2023-06-15',
      createdAt: '2024-01-04'
    },
    {
      id: 'ase2',
      type: 'asesor',
      name: 'Carlos Rodríguez',
      email: 'carlos.rodriguez@hb.local',
      phone: '+573001112237',
      whatsapp: '+573001112237',
      active: true,
      department: 'Soporte',
      position: 'Asesor Técnico',
      hireDate: '2023-08-20',
      createdAt: '2024-01-05'
    },
    {
      id: 'ase3',
      type: 'asesor',
      name: 'Ana Martínez',
      email: 'ana.martinez@hb.local',
      phone: '+573001112238',
      whatsapp: '+573001112238',
      active: false,
      department: 'Ventas',
      position: 'Asesor Junior',
      hireDate: '2023-12-01',
      createdAt: '2024-01-06'
    }
  ],

  // Categorías de productos
  categories: [
    { id: 'cat1', name: 'Pilas', icon: '🔋', description: 'Pilas recargables y desechables' },
    { id: 'cat2', name: 'Cargadores', icon: '🔌', description: 'Cargadores universales y específicos' },
    { id: 'cat3', name: 'Laptops', icon: '💻', description: 'Computadores portátiles' },
    { id: 'cat4', name: 'Accesorios', icon: '🎧', description: 'Accesorios para dispositivos' },
    { id: 'cat5', name: 'Audio', icon: '🔊', description: 'Equipos de audio y sonido' },
    { id: 'cat6', name: 'Gaming', icon: '🎮', description: 'Productos para gaming' },
    { id: 'cat7', name: 'Smartphones', icon: '📱', description: 'Teléfonos inteligentes y celulares' },
    { id: 'cat8', name: 'Tablets', icon: '📱', description: 'Tablets y dispositivos móviles' },
    { id: 'cat9', name: 'Monitores', icon: '🖥️', description: 'Monitores y pantallas' },
    { id: 'cat10', name: 'Componentes PC', icon: '🔧', description: 'Componentes para computadoras' },
    { id: 'cat11', name: 'TVs', icon: '📺', description: 'Televisores y smart TVs' },
    { id: 'cat12', name: 'Camaras', icon: '📷', description: 'Cámaras y fotografía' }
  ],

  // Productos del catálogo
  products: [
    {
      id: 'p1',
      owner: 'd1',
      name: 'Pila Recargable AA 2500mAh',
      description: 'Pila recargable de alta capacidad, ideal para dispositivos de alto consumo',
      pricePublico: 25000,
      priceDistribuidor: 18000,
      category: 'Pilas',
      stock: 50,
      image: '',
      sku: 'PIL-AA-2500',
      brand: 'Energizer',
      featured: true,
      sales: 15,
      createdAt: '2024-01-01'
    },
    {
      id: 'p2',
      owner: 'd1',
      name: 'Cargador Universal USB-C 65W',
      description: 'Cargador rápido universal compatible con múltiples dispositivos',
      pricePublico: 89000,
      priceDistribuidor: 65000,
      category: 'Cargadores',
      stock: 25,
      image: '',
      sku: 'CAR-USB65W',
      brand: 'Anker',
      featured: true,
      sales: 8,
      createdAt: '2024-01-02'
    },
    {
      id: 'p3',
      owner: 'd1',
      name: 'Laptop ASUS X1605VA Core i7',
      description: 'Laptop profesional con procesador Intel Core i7, 16GB RAM, 1TB SSD',
      pricePublico: 2850000,
      priceDistribuidor: 2200000,
      category: 'Laptops',
      stock: 3,
      image: '',
      sku: 'LAP-ASUS-X1605',
      brand: 'ASUS',
      featured: true,
      sales: 2,
      createdAt: '2024-01-03'
    },
    {
      id: 'p4',
      owner: 'd1',
      name: 'Auriculares Bluetooth Sony WH-1000XM4',
      description: 'Auriculares inalámbricos con cancelación de ruido activa',
      pricePublico: 1200000,
      priceDistribuidor: 950000,
      category: 'Audio',
      stock: 8,
      image: '',
      sku: 'AUD-SONY-WH1000',
      brand: 'Sony',
      featured: false,
      sales: 5,
      createdAt: '2024-01-04'
    },
    {
      id: 'p5',
      owner: 'd1',
      name: 'Mouse Gaming Logitech G502',
      description: 'Mouse gaming de alta precisión con 11 botones programables',
      pricePublico: 180000,
      priceDistribuidor: 135000,
      category: 'Gaming',
      stock: 12,
      image: '',
      sku: 'GAM-LOG-G502',
      brand: 'Logitech',
      featured: false,
      sales: 7,
      createdAt: '2024-01-05'
    },
    {
      id: 'p6',
      owner: 'd1',
      name: 'Pila Recargable AAA 1000mAh',
      description: 'Pila recargable compacta para dispositivos pequeños',
      pricePublico: 18000,
      priceDistribuidor: 13000,
      category: 'Pilas',
      stock: 35,
      image: '',
      sku: 'PIL-AAA-1000',
      brand: 'Duracell',
      featured: false,
      sales: 12,
      createdAt: '2024-01-06'
    },
    {
      id: 'p7',
      owner: 'd1',
      name: 'Cargador Inalámbrico 15W',
      description: 'Base de carga inalámbrica rápida para smartphones',
      pricePublico: 45000,
      priceDistribuidor: 32000,
      category: 'Cargadores',
      stock: 18,
      image: '',
      sku: 'CAR-WIRELESS-15W',
      brand: 'Samsung',
      featured: false,
      sales: 6,
      createdAt: '2024-01-07'
    },
    {
      id: 'p8',
      owner: 'd1',
      name: 'Laptop HP ProBook 450 G10',
      description: 'Laptop empresarial con Core i5, 8GB RAM, 256GB SSD',
      pricePublico: 2100000,
      priceDistribuidor: 1650000,
      category: 'Laptops',
      stock: 5,
      image: '',
      sku: 'LAP-HP-PB450',
      brand: 'HP',
      featured: true,
      sales: 3,
      createdAt: '2024-01-08'
    },
    {
      id: 'p9',
      owner: 'd1',
      name: 'Teclado Mecánico RGB',
      description: 'Teclado mecánico gaming con retroiluminación RGB',
      pricePublico: 320000,
      priceDistribuidor: 240000,
      category: 'Gaming',
      stock: 7,
      image: '',
      sku: 'GAM-KB-RGB',
      brand: 'Corsair',
      featured: false,
      sales: 4,
      createdAt: '2024-01-09'
    },
    {
      id: 'p10',
      owner: 'd1',
      name: 'Altavoz Bluetooth JBL Charge 4',
      description: 'Altavoz portátil resistente al agua con gran autonomía',
      pricePublico: 280000,
      priceDistribuidor: 210000,
      category: 'Audio',
      stock: 10,
      image: '',
      sku: 'AUD-JBL-CHARGE4',
      brand: 'JBL',
      featured: false,
      sales: 8,
      createdAt: '2024-01-10'
    },
    {
      id: 'p11',
      owner: 'd1',
      name: 'Cable USB-C a USB-C 2m',
      description: 'Cable de datos y carga de alta velocidad',
      pricePublico: 25000,
      priceDistribuidor: 18000,
      category: 'Accesorios',
      stock: 30,
      image: '',
      sku: 'ACC-USB-C-2M',
      brand: 'Anker',
      featured: false,
      sales: 15,
      createdAt: '2024-01-11'
    },
    {
      id: 'p12',
      owner: 'd1',
      name: 'Monitor 24" Full HD',
      description: 'Monitor LED 24 pulgadas con resolución Full HD',
      pricePublico: 450000,
      priceDistribuidor: 340000,
      category: 'Accesorios',
      stock: 6,
      image: '',
      sku: 'ACC-MON-24FHD',
      brand: 'LG',
      featured: false,
      sales: 2,
      createdAt: '2024-01-12'
    },
    {
      id: 'p13',
      owner: 'd1',
      name: 'Pila Recargable 9V 600mAh',
      description: 'Pila recargable para instrumentos musicales y equipos profesionales',
      pricePublico: 35000,
      priceDistribuidor: 25000,
      category: 'Pilas',
      stock: 15,
      image: '',
      sku: 'PIL-9V-600',
      brand: 'Energizer',
      featured: false,
      sales: 3,
      createdAt: '2024-01-13'
    },
    {
      id: 'p14',
      owner: 'd1',
      name: 'Cargador Múltiple 4 Puertos',
      description: 'Cargador de pared con 4 puertos USB para múltiples dispositivos',
      pricePublico: 65000,
      priceDistribuidor: 48000,
      category: 'Cargadores',
      stock: 20,
      image: '',
      sku: 'CAR-MULTI-4USB',
      brand: 'Anker',
      featured: false,
      sales: 9,
      createdAt: '2024-01-14'
    },
    {
      id: 'p15',
      owner: 'd1',
      name: 'Laptop Dell Inspiron 15 3000',
      description: 'Laptop básica con procesador Intel Core i3, 4GB RAM, 128GB SSD',
      pricePublico: 1650000,
      priceDistribuidor: 1250000,
      category: 'Laptops',
      stock: 4,
      image: '',
      sku: 'LAP-DELL-INS15',
      brand: 'Dell',
      featured: false,
      sales: 1,
      createdAt: '2024-01-15'
    },
    {
      id: 'p16',
      owner: 'd1',
      name: 'Micrófono USB Condensador',
      description: 'Micrófono de estudio para streaming y grabación',
      pricePublico: 180000,
      priceDistribuidor: 135000,
      category: 'Audio',
      stock: 8,
      image: '',
      sku: 'AUD-MIC-USB',
      brand: 'Blue',
      featured: false,
      sales: 4,
      createdAt: '2024-01-16'
    },
    {
      id: 'p17',
      owner: 'd1',
      name: 'Mouse Pad Gaming XL',
      description: 'Alfombrilla gaming extra grande con superficie optimizada',
      pricePublico: 35000,
      priceDistribuidor: 26000,
      category: 'Gaming',
      stock: 25,
      image: '',
      sku: 'GAM-PAD-XL',
      brand: 'SteelSeries',
      featured: false,
      sales: 11,
      createdAt: '2024-01-17'
    },
    {
      id: 'p18',
      owner: 'd1',
      name: 'Hub USB 3.0 7 Puertos',
      description: 'Concentrador USB con 7 puertos para expandir conectividad',
      pricePublico: 85000,
      priceDistribuidor: 62000,
      category: 'Accesorios',
      stock: 12,
      image: '',
      sku: 'ACC-HUB-USB7',
      brand: 'ORICO',
      featured: false,
      sales: 6,
      createdAt: '2024-01-18'
    },
    {
      id: 'p19',
      owner: 'd1',
      name: 'Pila Recargable D 8000mAh',
      description: 'Pila recargable de gran capacidad para equipos de alto consumo',
      pricePublico: 45000,
      priceDistribuidor: 32000,
      category: 'Pilas',
      stock: 8,
      image: '',
      sku: 'PIL-D-8000',
      brand: 'Duracell',
      featured: false,
      sales: 2,
      createdAt: '2024-01-19'
    },
    {
      id: 'p20',
      owner: 'd1',
      name: 'Cargador Solar Portátil 20000mAh',
      description: 'Power bank con panel solar integrado para carga ecológica',
      pricePublico: 120000,
      priceDistribuidor: 89000,
      category: 'Cargadores',
      stock: 6,
      image: '',
      sku: 'CAR-SOLAR-20K',
      brand: 'Anker',
      featured: true,
      sales: 3,
      createdAt: '2024-01-20'
    },
    // ===== SMARTPHONES =====
    {
      id: 'p21',
      owner: 'd1',
      name: 'iPhone 15 Pro 128GB',
      description: 'iPhone 15 Pro con chip A17 Pro, cámara de 48MP y pantalla Super Retina XDR',
      pricePublico: 4500000,
      priceDistribuidor: 3800000,
      category: 'Smartphones',
      stock: 8,
      image: '',
      sku: 'PHN-IPH15PRO-128',
      brand: 'Apple',
      featured: true,
      sales: 12,
      createdAt: '2024-01-21'
    },
    {
      id: 'p22',
      owner: 'd1',
      name: 'Samsung Galaxy S24 Ultra 256GB',
      description: 'Galaxy S24 Ultra con S Pen, cámara de 200MP y pantalla Dynamic AMOLED 2X',
      pricePublico: 4200000,
      priceDistribuidor: 3500000,
      category: 'Smartphones',
      stock: 6,
      image: '',
      sku: 'PHN-GAL-S24U-256',
      brand: 'Samsung',
      featured: true,
      sales: 8,
      createdAt: '2024-01-22'
    },
    {
      id: 'p23',
      owner: 'd1',
      name: 'Google Pixel 8 Pro 128GB',
      description: 'Pixel 8 Pro con Tensor G3, cámara de 50MP y Android 14',
      pricePublico: 3200000,
      priceDistribuidor: 2700000,
      category: 'Smartphones',
      stock: 10,
      image: '',
      sku: 'PHN-PIX8PRO-128',
      brand: 'Google',
      featured: false,
      sales: 5,
      createdAt: '2024-01-23'
    },
    {
      id: 'p24',
      owner: 'd1',
      name: 'OnePlus 12 256GB',
      description: 'OnePlus 12 con Snapdragon 8 Gen 3, cámara Hasselblad y carga rápida de 100W',
      pricePublico: 2800000,
      priceDistribuidor: 2300000,
      category: 'Smartphones',
      stock: 7,
      image: '',
      sku: 'PHN-OP12-256',
      brand: 'OnePlus',
      featured: false,
      sales: 4,
      createdAt: '2024-01-24'
    },
    {
      id: 'p25',
      owner: 'd1',
      name: 'Xiaomi Redmi Note 13 Pro 128GB',
      description: 'Redmi Note 13 Pro con cámara de 200MP, pantalla AMOLED y carga rápida',
      pricePublico: 1200000,
      priceDistribuidor: 950000,
      category: 'Smartphones',
      stock: 15,
      image: '',
      sku: 'PHN-XIA-RN13P-128',
      brand: 'Xiaomi',
      featured: false,
      sales: 18,
      createdAt: '2024-01-25'
    },
    // ===== TABLETS =====
    {
      id: 'p26',
      owner: 'd1',
      name: 'iPad Pro 12.9" M4 256GB',
      description: 'iPad Pro con chip M4, pantalla Liquid Retina XDR y Apple Pencil compatible',
      pricePublico: 5200000,
      priceDistribuidor: 4500000,
      category: 'Tablets',
      stock: 4,
      image: '',
      sku: 'TAB-IPADP-12.9-M4',
      brand: 'Apple',
      featured: true,
      sales: 3,
      createdAt: '2024-01-26'
    },
    {
      id: 'p27',
      owner: 'd1',
      name: 'Samsung Galaxy Tab S9 Ultra 256GB',
      description: 'Galaxy Tab S9 Ultra con S Pen, pantalla AMOLED y Android 13',
      pricePublico: 3800000,
      priceDistribuidor: 3200000,
      category: 'Tablets',
      stock: 5,
      image: '',
      sku: 'TAB-GAL-S9U-256',
      brand: 'Samsung',
      featured: false,
      sales: 2,
      createdAt: '2024-01-27'
    },
    {
      id: 'p28',
      owner: 'd1',
      name: 'iPad Air 10.9" M2 64GB',
      description: 'iPad Air con chip M2, pantalla Liquid Retina y Touch ID',
      pricePublico: 2800000,
      priceDistribuidor: 2400000,
      category: 'Tablets',
      stock: 8,
      image: '',
      sku: 'TAB-IPADA-M2-64',
      brand: 'Apple',
      featured: false,
      sales: 6,
      createdAt: '2024-01-28'
    },
    {
      id: 'p29',
      owner: 'd1',
      name: 'Lenovo Tab P11 Pro Gen 2 128GB',
      description: 'Tab P11 Pro con pantalla OLED, altavoces JBL y Android 12',
      pricePublico: 1800000,
      priceDistribuidor: 1500000,
      category: 'Tablets',
      stock: 6,
      image: '',
      sku: 'TAB-LEN-P11P2-128',
      brand: 'Lenovo',
      featured: false,
      sales: 4,
      createdAt: '2024-01-29'
    },
    // ===== MONITORES =====
    {
      id: 'p30',
      owner: 'd1',
      name: 'Monitor Gaming ASUS ROG 27" 4K 144Hz',
      description: 'Monitor gaming 4K con 144Hz, G-Sync y HDR600',
      pricePublico: 2800000,
      priceDistribuidor: 2200000,
      category: 'Monitores',
      stock: 3,
      image: '',
      sku: 'MON-ASUS-ROG27-4K',
      brand: 'ASUS',
      featured: true,
      sales: 1,
      createdAt: '2024-01-30'
    },
    {
      id: 'p31',
      owner: 'd1',
      name: 'Monitor Dell UltraSharp 32" 4K',
      description: 'Monitor profesional 4K con 99% sRGB y USB-C',
      pricePublico: 3200000,
      priceDistribuidor: 2600000,
      category: 'Monitores',
      stock: 4,
      image: '',
      sku: 'MON-DELL-U32-4K',
      brand: 'Dell',
      featured: false,
      sales: 2,
      createdAt: '2024-01-31'
    },
    {
      id: 'p32',
      owner: 'd1',
      name: 'Monitor LG UltraGear 24" 165Hz',
      description: 'Monitor gaming Full HD con 165Hz y G-Sync compatible',
      pricePublico: 850000,
      priceDistribuidor: 680000,
      category: 'Monitores',
      stock: 8,
      image: '',
      sku: 'MON-LG-UG24-165',
      brand: 'LG',
      featured: false,
      sales: 5,
      createdAt: '2024-02-01'
    },
    {
      id: 'p33',
      owner: 'd1',
      name: 'Monitor Curvo Samsung 34" UltraWide',
      description: 'Monitor curvo ultra ancho QHD con 100Hz y FreeSync',
      pricePublico: 1800000,
      priceDistribuidor: 1450000,
      category: 'Monitores',
      stock: 5,
      image: '',
      sku: 'MON-SAM-CURV34-UW',
      brand: 'Samsung',
      featured: false,
      sales: 3,
      createdAt: '2024-02-02'
    },
    // ===== COMPONENTES PC =====
    {
      id: 'p34',
      owner: 'd1',
      name: 'RTX 4080 Super 16GB GDDR6X',
      description: 'Tarjeta gráfica gaming de alta gama con ray tracing',
      pricePublico: 4200000,
      priceDistribuidor: 3500000,
      category: 'Componentes PC',
      stock: 2,
      image: '',
      sku: 'GPU-RTX4080S-16G',
      brand: 'NVIDIA',
      featured: true,
      sales: 1,
      createdAt: '2024-02-03'
    },
    {
      id: 'p35',
      owner: 'd1',
      name: 'Intel Core i9-14900K',
      description: 'Procesador Intel Core i9 de 14va generación con 24 núcleos',
      pricePublico: 2800000,
      priceDistribuidor: 2200000,
      category: 'Componentes PC',
      stock: 3,
      image: '',
      sku: 'CPU-INT-I9-14900K',
      brand: 'Intel',
      featured: false,
      sales: 2,
      createdAt: '2024-02-04'
    },
    {
      id: 'p36',
      owner: 'd1',
      name: 'AMD Ryzen 9 7950X',
      description: 'Procesador AMD Ryzen 9 con 16 núcleos y 32 hilos',
      pricePublico: 2500000,
      priceDistribuidor: 2000000,
      category: 'Componentes PC',
      stock: 4,
      image: '',
      sku: 'CPU-AMD-R9-7950X',
      brand: 'AMD',
      featured: false,
      sales: 3,
      createdAt: '2024-02-05'
    },
    {
      id: 'p37',
      owner: 'd1',
      name: 'RAM DDR5 32GB 5600MHz',
      description: 'Memoria RAM DDR5 de alta velocidad para gaming y trabajo',
      pricePublico: 650000,
      priceDistribuidor: 520000,
      category: 'Componentes PC',
      stock: 12,
      image: '',
      sku: 'RAM-DDR5-32G-5600',
      brand: 'Corsair',
      featured: false,
      sales: 8,
      createdAt: '2024-02-06'
    },
    {
      id: 'p38',
      owner: 'd1',
      name: 'SSD NVMe 2TB PCIe 4.0',
      description: 'Disco sólido NVMe de alta velocidad para almacenamiento rápido',
      pricePublico: 850000,
      priceDistribuidor: 680000,
      category: 'Componentes PC',
      stock: 10,
      image: '',
      sku: 'SSD-NVME-2TB-PCI4',
      brand: 'Samsung',
      featured: false,
      sales: 6,
      createdAt: '2024-02-07'
    },
    {
      id: 'p39',
      owner: 'd1',
      name: 'Motherboard ASUS ROG Strix Z790',
      description: 'Placa madre gaming con soporte para Intel 12va y 13va gen',
      pricePublico: 1200000,
      priceDistribuidor: 950000,
      category: 'Componentes PC',
      stock: 6,
      image: '',
      sku: 'MB-ASUS-ROG-Z790',
      brand: 'ASUS',
      featured: false,
      sales: 4,
      createdAt: '2024-02-08'
    },
    // ===== TVs =====
    {
      id: 'p40',
      owner: 'd1',
      name: 'Smart TV Samsung 65" QLED 4K',
      description: 'Smart TV QLED 4K con Tizen OS y Alexa integrada',
      pricePublico: 4200000,
      priceDistribuidor: 3500000,
      category: 'TVs',
      stock: 3,
      image: '',
      sku: 'TV-SAM-65-Q4K',
      brand: 'Samsung',
      featured: true,
      sales: 2,
      createdAt: '2024-02-09'
    },
    {
      id: 'p41',
      owner: 'd1',
      name: 'Smart TV LG 55" OLED 4K',
      description: 'Smart TV OLED 4K con webOS y Magic Remote',
      pricePublico: 3800000,
      priceDistribuidor: 3200000,
      category: 'TVs',
      stock: 4,
      image: '',
      sku: 'TV-LG-55-O4K',
      brand: 'LG',
      featured: false,
      sales: 1,
      createdAt: '2024-02-10'
    },
    {
      id: 'p42',
      owner: 'd1',
      name: 'Smart TV Sony 75" LED 4K',
      description: 'Smart TV LED 4K con Android TV y Google Assistant',
      pricePublico: 5200000,
      priceDistribuidor: 4500000,
      category: 'TVs',
      stock: 2,
      image: '',
      sku: 'TV-SON-75-L4K',
      brand: 'Sony',
      featured: false,
      sales: 1,
      createdAt: '2024-02-11'
    },
    // ===== CÁMARAS =====
    {
      id: 'p43',
      owner: 'd1',
      name: 'Canon EOS R6 Mark II',
      description: 'Cámara mirrorless full frame con 24.2MP y grabación 4K',
      pricePublico: 5200000,
      priceDistribuidor: 4500000,
      category: 'Camaras',
      stock: 2,
      image: '',
      sku: 'CAM-CAN-R6M2',
      brand: 'Canon',
      featured: true,
      sales: 1,
      createdAt: '2024-02-12'
    },
    {
      id: 'p44',
      owner: 'd1',
      name: 'Sony A7 IV Mirrorless',
      description: 'Cámara mirrorless full frame con 33MP y estabilización IBIS',
      pricePublico: 4800000,
      priceDistribuidor: 4000000,
      category: 'Camaras',
      stock: 3,
      image: '',
      sku: 'CAM-SON-A7IV',
      brand: 'Sony',
      featured: false,
      sales: 2,
      createdAt: '2024-02-13'
    },
    {
      id: 'p45',
      owner: 'd1',
      name: 'GoPro Hero 12 Black',
      description: 'Cámara de acción 4K con estabilización HyperSmooth 6.0',
      pricePublico: 650000,
      priceDistribuidor: 520000,
      category: 'Camaras',
      stock: 8,
      image: '',
      sku: 'CAM-GOP-H12B',
      brand: 'GoPro',
      featured: false,
      sales: 5,
      createdAt: '2024-02-14'
    },
    // ===== MÁS PRODUCTOS GAMING =====
    {
      id: 'p46',
      owner: 'd1',
      name: 'Consola PlayStation 5',
      description: 'Consola de videojuegos de nueva generación con SSD ultra rápido',
      pricePublico: 2800000,
      priceDistribuidor: 2200000,
      category: 'Gaming',
      stock: 5,
      image: '',
      sku: 'GAM-PS5-STD',
      brand: 'Sony',
      featured: true,
      sales: 8,
      createdAt: '2024-02-15'
    },
    {
      id: 'p47',
      owner: 'd1',
      name: 'Consola Xbox Series X',
      description: 'Consola de videojuegos con 4K nativo y Quick Resume',
      pricePublico: 2600000,
      priceDistribuidor: 2100000,
      category: 'Gaming',
      stock: 4,
      image: '',
      sku: 'GAM-XBX-SX',
      brand: 'Microsoft',
      featured: false,
      sales: 6,
      createdAt: '2024-02-16'
    },
    {
      id: 'p48',
      owner: 'd1',
      name: 'Nintendo Switch OLED',
      description: 'Consola híbrida con pantalla OLED de 7 pulgadas',
      pricePublico: 1800000,
      priceDistribuidor: 1450000,
      category: 'Gaming',
      stock: 7,
      image: '',
      sku: 'GAM-NSW-OLED',
      brand: 'Nintendo',
      featured: false,
      sales: 9,
      createdAt: '2024-02-17'
    },
    {
      id: 'p49',
      owner: 'd1',
      name: 'Silla Gaming RGB',
      description: 'Silla gaming ergonómica con iluminación RGB y soporte lumbar',
      pricePublico: 650000,
      priceDistribuidor: 520000,
      category: 'Gaming',
      stock: 6,
      image: '',
      sku: 'GAM-CHAIR-RGB',
      brand: 'Razer',
      featured: false,
      sales: 4,
      createdAt: '2024-02-18'
    },
    {
      id: 'p50',
      owner: 'd1',
      name: 'Stream Deck 15 Teclas',
      description: 'Panel de control para streamers y creadores de contenido',
      pricePublico: 380000,
      priceDistribuidor: 300000,
      category: 'Gaming',
      stock: 8,
      image: '',
      sku: 'GAM-STREAM-DECK15',
      brand: 'Elgato',
      featured: false,
      sales: 3,
      createdAt: '2024-02-19'
    },
    // ===== MÁS PRODUCTOS DE AUDIO =====
    {
      id: 'p51',
      owner: 'd1',
      name: 'AirPods Pro 2da Gen',
      description: 'Auriculares inalámbricos con cancelación activa de ruido',
      pricePublico: 850000,
      priceDistribuidor: 680000,
      category: 'Audio',
      stock: 12,
      image: '',
      sku: 'AUD-APRO-G2',
      brand: 'Apple',
      featured: false,
      sales: 15,
      createdAt: '2024-02-20'
    },
    {
      id: 'p52',
      owner: 'd1',
      name: 'Sistema de Sonido 5.1 Bose',
      description: 'Sistema de audio surround 5.1 para cine en casa',
      pricePublico: 2800000,
      priceDistribuidor: 2200000,
      category: 'Audio',
      stock: 3,
      image: '',
      sku: 'AUD-BOSE-5.1',
      brand: 'Bose',
      featured: false,
      sales: 1,
      createdAt: '2024-02-21'
    },
    {
      id: 'p53',
      owner: 'd1',
      name: 'Auriculares Beats Studio3',
      description: 'Auriculares over-ear con cancelación de ruido y Pure ANC',
      pricePublico: 650000,
      priceDistribuidor: 520000,
      category: 'Audio',
      stock: 8,
      image: '',
      sku: 'AUD-BEATS-ST3',
      brand: 'Beats',
      featured: false,
      sales: 6,
      createdAt: '2024-02-22'
    },
    {
      id: 'p54',
      owner: 'd1',
      name: 'Altavoz Inteligente Echo Dot',
      description: 'Altavoz inteligente con Alexa y control por voz',
      pricePublico: 120000,
      priceDistribuidor: 95000,
      category: 'Audio',
      stock: 15,
      image: '',
      sku: 'AUD-ECHO-DOT4',
      brand: 'Amazon',
      featured: false,
      sales: 12,
      createdAt: '2024-02-23'
    },
    // ===== MÁS ACCESORIOS =====
    {
      id: 'p55',
      owner: 'd1',
      name: 'Apple Watch Series 9 GPS',
      description: 'Smartwatch con pantalla Always-On y detección de caídas',
      pricePublico: 1200000,
      priceDistribuidor: 950000,
      category: 'Accesorios',
      stock: 10,
      image: '',
      sku: 'ACC-AW-S9-GPS',
      brand: 'Apple',
      featured: false,
      sales: 8,
      createdAt: '2024-02-24'
    },
    {
      id: 'p56',
      owner: 'd1',
      name: 'Samsung Galaxy Watch6 Classic',
      description: 'Smartwatch con rotación de bisel y monitoreo de salud',
      pricePublico: 850000,
      priceDistribuidor: 680000,
      category: 'Accesorios',
      stock: 8,
      image: '',
      sku: 'ACC-GW6-CLASSIC',
      brand: 'Samsung',
      featured: false,
      sales: 5,
      createdAt: '2024-02-25'
    },
    {
      id: 'p57',
      owner: 'd1',
      name: 'Fundas iPhone 15 Pro Max',
      description: 'Set de fundas protectoras para iPhone 15 Pro Max',
      pricePublico: 85000,
      priceDistribuidor: 65000,
      category: 'Accesorios',
      stock: 25,
      image: '',
      sku: 'ACC-CASE-IP15PM',
      brand: 'Spigen',
      featured: false,
      sales: 18,
      createdAt: '2024-02-26'
    },
    {
      id: 'p58',
      owner: 'd1',
      name: 'Protectores Pantalla Cristal',
      description: 'Protectores de pantalla en cristal templado para smartphones',
      pricePublico: 35000,
      priceDistribuidor: 26000,
      category: 'Accesorios',
      stock: 40,
      image: '',
      sku: 'ACC-PROT-CRYSTAL',
      brand: 'Tempered',
      featured: false,
      sales: 25,
      createdAt: '2024-02-27'
    },
    {
      id: 'p59',
      owner: 'd1',
      name: 'Cable Lightning 1m Original',
      description: 'Cable Lightning original de Apple para iPhone e iPad',
      pricePublico: 45000,
      priceDistribuidor: 35000,
      category: 'Accesorios',
      stock: 30,
      image: '',
      sku: 'ACC-CABLE-LIGHT1M',
      brand: 'Apple',
      featured: false,
      sales: 20,
      createdAt: '2024-02-28'
    },
    {
      id: 'p60',
      owner: 'd1',
      name: 'Adaptador USB-C a HDMI',
      description: 'Adaptador para conectar dispositivos USB-C a monitores HDMI',
      pricePublico: 65000,
      priceDistribuidor: 48000,
      category: 'Accesorios',
      stock: 20,
      image: '',
      sku: 'ACC-ADP-USBC-HDMI',
      brand: 'Anker',
      featured: false,
      sales: 8,
      createdAt: '2024-02-29'
    },
    // ===== MÁS PRODUCTOS PARA COMPLETAR CATEGORÍAS =====
    // Más Pilas (para llegar a 5+)
    {
      id: 'p61',
      owner: 'd1',
      name: 'Pila Recargable C 5000mAh',
      description: 'Pila recargable tipo C de alta capacidad para equipos de uso intensivo',
      pricePublico: 38000,
      priceDistribuidor: 28000,
      category: 'Pilas',
      stock: 12,
      image: '',
      sku: 'PIL-C-5000',
      brand: 'Energizer',
      featured: false,
      sales: 5,
      createdAt: '2024-03-01'
    },
    {
      id: 'p62',
      owner: 'd1',
      name: 'Set Pilas Recargables AA/AAA',
      description: 'Set de 8 pilas recargables (4 AA + 4 AAA) con cargador incluido',
      pricePublico: 120000,
      priceDistribuidor: 89000,
      category: 'Pilas',
      stock: 8,
      image: '',
      sku: 'PIL-SET-AA-AAA',
      brand: 'Duracell',
      featured: false,
      sales: 7,
      createdAt: '2024-03-02'
    },
    // Más Cargadores (para llegar a 5+)
    {
      id: 'p63',
      owner: 'd1',
      name: 'Cargador MagSafe iPhone',
      description: 'Cargador inalámbrico MagSafe compatible con iPhone 12/13/14/15',
      pricePublico: 180000,
      priceDistribuidor: 135000,
      category: 'Cargadores',
      stock: 10,
      image: '',
      sku: 'CAR-MAGSAFE-IPH',
      brand: 'Apple',
      featured: false,
      sales: 12,
      createdAt: '2024-03-03'
    },
    {
      id: 'p64',
      owner: 'd1',
      name: 'Cargador Vehicular USB-C 30W',
      description: 'Cargador para vehículo con USB-C de 30W y puerto USB-A adicional',
      pricePublico: 75000,
      priceDistribuidor: 55000,
      category: 'Cargadores',
      stock: 15,
      image: '',
      sku: 'CAR-VEH-USB30W',
      brand: 'Anker',
      featured: false,
      sales: 9,
      createdAt: '2024-03-04'
    },
    // Más Laptops (para llegar a 5+)
    {
      id: 'p65',
      owner: 'd1',
      name: 'Laptop Lenovo ThinkPad E15',
      description: 'Laptop empresarial con AMD Ryzen 5, 8GB RAM, 256GB SSD',
      pricePublico: 1950000,
      priceDistribuidor: 1550000,
      category: 'Laptops',
      stock: 4,
      image: '',
      sku: 'LAP-LEN-THINKPAD-E15',
      brand: 'Lenovo',
      featured: false,
      sales: 2,
      createdAt: '2024-03-05'
    },
    {
      id: 'p66',
      owner: 'd1',
      name: 'Laptop Acer Aspire 5 Gaming',
      description: 'Laptop gaming con Intel i5, 8GB RAM, 512GB SSD, GTX 1650',
      pricePublico: 2200000,
      priceDistribuidor: 1750000,
      category: 'Laptops',
      stock: 3,
      image: '',
      sku: 'LAP-ACER-ASP5-GAM',
      brand: 'Acer',
      featured: false,
      sales: 4,
      createdAt: '2024-03-06'
    },
    // Más Monitores (para llegar a 5+)
    {
      id: 'p67',
      owner: 'd1',
      name: 'Monitor Gaming MSI 27" 144Hz',
      description: 'Monitor gaming Full HD con 144Hz, FreeSync y diseño gaming',
      pricePublico: 950000,
      priceDistribuidor: 750000,
      category: 'Monitores',
      stock: 6,
      image: '',
      sku: 'MON-MSI-27-144',
      brand: 'MSI',
      featured: false,
      sales: 3,
      createdAt: '2024-03-07'
    },
    // Más Componentes PC (para llegar a 5+)
    {
      id: 'p68',
      owner: 'd1',
      name: 'Fuente de Poder 850W 80+ Gold',
      description: 'Fuente de poder modular 850W con certificación 80+ Gold',
      pricePublico: 650000,
      priceDistribuidor: 520000,
      category: 'Componentes PC',
      stock: 8,
      image: '',
      sku: 'PSU-850W-GOLD',
      brand: 'Corsair',
      featured: false,
      sales: 5,
      createdAt: '2024-03-08'
    },
    {
      id: 'p69',
      owner: 'd1',
      name: 'Cooler CPU AIO 240mm RGB',
      description: 'Enfriador líquido para CPU con radiador de 240mm y RGB',
      pricePublico: 420000,
      priceDistribuidor: 320000,
      category: 'Componentes PC',
      stock: 5,
      image: '',
      sku: 'COOL-AIO-240RGB',
      brand: 'NZXT',
      featured: false,
      sales: 3,
      createdAt: '2024-03-09'
    },
    {
      id: 'p70',
      owner: 'd1',
      name: 'Case Gaming RGB ATX Mid Tower',
      description: 'Gabinete gaming con iluminación RGB y ventiladores incluidos',
      pricePublico: 380000,
      priceDistribuidor: 290000,
      category: 'Componentes PC',
      stock: 7,
      image: '',
      sku: 'CASE-GAM-RGB-ATX',
      brand: 'Corsair',
      featured: false,
      sales: 4,
      createdAt: '2024-03-10'
    },
    // Más TVs (para llegar a 5+)
    {
      id: 'p71',
      owner: 'd1',
      name: 'Smart TV TCL 43" 4K Android',
      description: 'Smart TV 4K con Android TV y Google Assistant',
      pricePublico: 1800000,
      priceDistribuidor: 1450000,
      category: 'TVs',
      stock: 5,
      image: '',
      sku: 'TV-TCL-43-4K-AND',
      brand: 'TCL',
      featured: false,
      sales: 2,
      createdAt: '2024-03-11'
    },
    {
      id: 'p72',
      owner: 'd1',
      name: 'Smart TV Hisense 50" 4K UHD',
      description: 'Smart TV 4K UHD con Vidaa OS y Dolby Vision',
      pricePublico: 2200000,
      priceDistribuidor: 1750000,
      category: 'TVs',
      stock: 4,
      image: '',
      sku: 'TV-HIS-50-4K-UHD',
      brand: 'Hisense',
      featured: false,
      sales: 1,
      createdAt: '2024-03-12'
    },
    // Más Cámaras (para llegar a 5+)
    {
      id: 'p73',
      owner: 'd1',
      name: 'Nikon D7500 DSLR',
      description: 'Cámara DSLR con sensor APS-C de 20.9MP y grabación 4K',
      pricePublico: 3800000,
      priceDistribuidor: 3200000,
      category: 'Camaras',
      stock: 3,
      image: '',
      sku: 'CAM-NIK-D7500',
      brand: 'Nikon',
      featured: false,
      sales: 2,
      createdAt: '2024-03-13'
    },
    {
      id: 'p74',
      owner: 'd1',
      name: 'DJI Mini 3 Drone',
      description: 'Drone compacto con cámara 4K, 3 ejes de estabilización',
      pricePublico: 2200000,
      priceDistribuidor: 1800000,
      category: 'Camaras',
      stock: 4,
      image: '',
      sku: 'CAM-DJI-MINI3',
      brand: 'DJI',
      featured: false,
      sales: 3,
      createdAt: '2024-03-14'
    },
    {
      id: 'p75',
      owner: 'd1',
      name: 'Insta360 One RS Cámara 360°',
      description: 'Cámara modular 360° con grabación 4K y estabilización',
      pricePublico: 1800000,
      priceDistribuidor: 1450000,
      category: 'Camaras',
      stock: 6,
      image: '',
      sku: 'CAM-INS-ONE-RS',
      brand: 'Insta360',
      featured: false,
      sales: 4,
      createdAt: '2024-03-15'
    }
  ],

  // Configuración del sistema
  config: {
    companyName: 'H&B Importaciones',
    companySlogan: 'Tecnología de vanguardia para tu éxito',
    whatsapp: '+573001112233',
    email: 'contacto@hbimportaciones.com',
    address: 'Calle 123 #45-67, Bogotá, Colombia',
    hours: 'Lunes a Viernes 09:00 a 18:00 | Sábados 09:00 a 13:00',
    socialMedia: {
      facebook: 'https://facebook.com/hbimportaciones',
      instagram: 'https://instagram.com/hbimportaciones',
      twitter: 'https://twitter.com/hbimportaciones'
    },
    currency: 'COP',
    currencySymbol: '$',
    lowStockThreshold: 5,
    featuredProductsCount: 6
  },

  // Slider hero banners
  heroSlides: [
    {
      id: 'slide1',
      title: 'DESKTOPS DE ALTO RENDIMIENTO',
      subtitle: 'Máxima potencia en un solo equipo',
      cta: 'Explorar Productos',
      ctaLink: 'src/user/store.html',
      background: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 50%, #1a1a1a 100%)',
      featured: true
    },
    {
      id: 'slide2',
      title: 'NUESTRA MISIÓN',
      subtitle: 'Proporcionar tecnología de vanguardia y soluciones informáticas de alta calidad para impulsar el éxito de nuestros clientes',
      cta: 'Conocer Más',
      ctaLink: 'src/user/store.html',
      background: 'linear-gradient(135deg, #0066cc 0%, #00aaff 50%, #0066cc 100%)',
      featured: false
    },
    {
      id: 'slide3',
      title: 'NUESTRA VISIÓN',
      subtitle: 'Ser la empresa líder en importación y distribución de tecnología, reconocida por nuestra excelencia y compromiso con la innovación',
      cta: 'Nuestros Valores',
      ctaLink: 'src/user/store.html',
      background: 'linear-gradient(135deg, #00aaff 0%, #0066cc 50%, #00aaff 100%)',
      featured: false
    },
    {
      id: 'slide4',
      title: 'COMPROMISO DE CALIDAD',
      subtitle: 'Garantizamos productos originales, soporte técnico especializado y entrega confiable en todo el territorio nacional',
      cta: 'Ver Garantías',
      ctaLink: 'src/user/store.html',
      background: 'linear-gradient(135deg, #2d2d2d 0%, #1a1a1a 50%, #2d2d2d 100%)',
      featured: false
    }
  ]
};

// Exportar datos para uso global
window.HBDATA = HBDATA;
